version: '3'

services:


  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: pereiraze/fullcycle_node
    container_name: app
    entrypoint: wait-for db:3306 -t 40 -- node src/index.js
    networks:
      - fullcycle
    tty: true
    depends_on:
      - db


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: pereiraze/fullcycle_nginx
    entrypoint: wait-for app:3000 -t 40 -- nginx -g 'daemon off;'
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - app


  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafio02_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
    


networks:
  fullcycle:
    driver: bridge


