apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: go-server # este name sera o mesmo informado no selector.matchLabels do deployment
  type: ClusterIP
  ports:
    - name: go-server-port
      port: 80
      protocol: TCP



