apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server-app
spec:
  selector:
    matchLabels:
      app: go-server
  replicas: 2
  template:
    metadata:
      labels:
        app: "go-server"
    spec:
      containers:
        - name: goserver
          image: "pereiraze/hello-go:latest"

